# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './modify_pixel_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 225)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.B_label = QtWidgets.QLabel(Form)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 1, 4, 1, 1)
        self.y_label = QtWidgets.QLabel(Form)
        self.y_label.setObjectName("y_label")
        self.gridLayout.addWidget(self.y_label, 0, 2, 1, 1)
        self.G_label = QtWidgets.QLabel(Form)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 1, 2, 1, 1)
        self.x_label = QtWidgets.QLabel(Form)
        self.x_label.setObjectName("x_label")
        self.gridLayout.addWidget(self.x_label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.R_label = QtWidgets.QLabel(Form)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.B_label.setText(_translate("Form", "B"))
        self.y_label.setText(_translate("Form", "Y"))
        self.G_label.setText(_translate("Form", "G"))
        self.x_label.setText(_translate("Form", "X"))
        self.R_label.setText(_translate("Form", "R"))
