# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHub\ATI_TPS\filters\guis\gauss_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 349)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mu = QtWidgets.QLabel(self.groupBox)
        self.mu.setStyleSheet("font-weight:bold;font-size:16px;")
        self.mu.setScaledContents(False)
        self.mu.setAlignment(QtCore.Qt.AlignCenter)
        self.mu.setObjectName("mu")
        self.horizontalLayout_2.addWidget(self.mu)
        self.mu_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.mu_line_edit.setObjectName("mu_line_edit")
        self.horizontalLayout_2.addWidget(self.mu_line_edit)
        spacerItem = QtWidgets.QSpacerItem(380, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 5)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mu.setText(_translate("Form", "<html><head/><body><pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:130.769%;\"><span style=\" font-family:\'inherit\'; font-size:16px; color:#000000; background-color:transparent;\"><p>&epsilon;</></span></pre></body></html>"))
